# link - https://www.machinelearningplus.com/python/101-numpy-exercises-python/

In [10]:
# 1. Import numpy as np and see the version
import numpy as np
np.__version__

'1.25.1'

In [11]:
# 2. How to create a 1D array?
# Difficulty Level: L1

# Q. Create a 1D array of numbers from 0 to 9

# Desired output:

# > array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

print(np.array(object=range(0, 10)))
print(np.arange(10))

[0 1 2 3 4 5 6 7 8 9]
[0 1 2 3 4 5 6 7 8 9]


In [14]:
# 3. How to create a boolean array?
# Difficulty Level: L1

# Q. Create a 3×3 numpy array of all True’s

print(np.full(shape=(3, 3), fill_value=True, dtype=bool))
print(np.ones(shape=(3, 3), dtype=bool))

[[ True  True  True]
 [ True  True  True]
 [ True  True  True]]
[[ True  True  True]
 [ True  True  True]
 [ True  True  True]]


In [16]:
# 4. How to extract items that satisfy a given condition from 1D array?
# Difficulty Level: L1

# Q. Extract all odd numbers from arr

# Input:

# arr = np.array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])
# Desired output:

# > array([1, 3, 5, 7, 9])
arr = np.array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])
condition = np.mod(arr, 2) != 0
np.extract(condition=condition, arr=arr)

array([1, 3, 5, 7, 9])