# link - https://www.machinelearningplus.com/python/101-numpy-exercises-python/

##### 1. Import numpy as np and see the version

In [34]:

import numpy as np
np.__version__

'1.25.1'

##### 2. How to create a 1D array?
##### Difficulty Level: L1
##### Q. Create a 1D array of numbers from 0 to 9
##### Desired output:
##### > array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [35]:
print(np.array(object=range(0, 10)))
print(np.arange(10))

[0 1 2 3 4 5 6 7 8 9]
[0 1 2 3 4 5 6 7 8 9]


In [36]:
# 3. How to create a boolean array?
# Difficulty Level: L1

# Q. Create a 3×3 numpy array of all True’s

print(np.full(shape=(3, 3), fill_value=True, dtype=bool))
print(np.ones(shape=(3, 3), dtype=bool))

[[ True  True  True]
 [ True  True  True]
 [ True  True  True]]
[[ True  True  True]
 [ True  True  True]
 [ True  True  True]]


In [37]:
# 4. How to extract items that satisfy a given condition from 1D array?
# Difficulty Level: L1

# Q. Extract all odd numbers from arr

# Input:

# arr = np.array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])
# Desired output:

# > array([1, 3, 5, 7, 9])
arr = np.array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])
condition = np.mod(arr, 2) != 0
print(np.extract(condition=condition, arr=arr))

print(arr[arr % 2 == 1])

[1 3 5 7 9]
[1 3 5 7 9]


In [38]:
# 5. How to replace items that satisfy a condition with another value in numpy array?
# Difficulty Level: L1

# Q. Replace all odd numbers in arr with -1

# Input:

# arr = np.array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])
# Desired Output:

# >  array([ 0, -1,  2, -1,  4, -1,  6, -1,  8, -1])
arr = np.array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])
arr[arr % 2 != 0] = -1
arr

array([ 0, -1,  2, -1,  4, -1,  6, -1,  8, -1])

In [39]:
# 6. How to replace items that satisfy a condition without affecting the original array?
# Difficulty Level: L2

# Q. Replace all odd numbers in arr with -1 without changing arr

# Input:

# arr = np.array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])
# Desired Output:
# out
# >  array([ 0, -1,  2, -1,  4, -1,  6, -1,  8, -1])
# arr
# >  array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])
arr = np.array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])
print(np.where(arr % 2 == 1, -1, arr))
print(arr)

[ 0 -1  2 -1  4 -1  6 -1  8 -1]
[0 1 2 3 4 5 6 7 8 9]


In [40]:
# 7. How to reshape an array?
# Difficulty Level: L1

# Q. Convert a 1D array to a 2D array with 2 rows

# Input:

# np.arange(10)

# > array([ 0, 1, 2, 3, 4, 5, 6, 7, 8, 9])
# Desired Output:

# > array([[0, 1, 2, 3, 4],
# >        [5, 6, 7, 8, 9]])
arr = np.arange(10)
print(arr)
print(arr.shape)
print(np.reshape(arr, (2, 5)))
arr2 = np.arange(10)
print(np.reshape(arr2, (2, -1)))

[0 1 2 3 4 5 6 7 8 9]
(10,)
[[0 1 2 3 4]
 [5 6 7 8 9]]
[[0 1 2 3 4]
 [5 6 7 8 9]]


In [41]:
# 8. How to stack two arrays vertically?
# Difficulty Level: L2

# Q. Stack arrays a and b vertically

# Input

# a = np.arange(10).reshape(2,-1)
# b = np.repeat(1, 10).reshape(2,-1)
# Desired Output:

# > array([[0, 1, 2, 3, 4],
# >        [5, 6, 7, 8, 9],
# >        [1, 1, 1, 1, 1],
# >        [1, 1, 1, 1, 1]])

a = np.arange(10).reshape(2, -1)
print(a)
b = np.repeat(1, 10).reshape(2, -1)
print(b)
print(np.append(a, b, axis=0))
print(np.concatenate([a, b], axis=0))
print(np.vstack((a, b)))
np.r_[a, b]

[[0 1 2 3 4]
 [5 6 7 8 9]]
[[1 1 1 1 1]
 [1 1 1 1 1]]
[[0 1 2 3 4]
 [5 6 7 8 9]
 [1 1 1 1 1]
 [1 1 1 1 1]]
[[0 1 2 3 4]
 [5 6 7 8 9]
 [1 1 1 1 1]
 [1 1 1 1 1]]
[[0 1 2 3 4]
 [5 6 7 8 9]
 [1 1 1 1 1]
 [1 1 1 1 1]]


array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1]])

In [42]:
# 9. How to stack two arrays horizontally?
# Difficulty Level: L2

# Q. Stack the arrays a and b horizontally.

# Input
# a = np.arange(10).reshape(2,-1)

# b = np.repeat(1, 10).reshape(2,-1)
# Desired Output:

# > array([[0, 1, 2, 3, 4, 1, 1, 1, 1, 1],
# >        [5, 6, 7, 8, 9, 1, 1, 1, 1, 1]])
a = np.arange(10).reshape(2, -1)
b = np.repeat(1, 10).reshape(2, -1)
print(np.hstack([a, b]))
print(np.concatenate([a, b], axis=1))
print(np.c_[a, b])

[[0 1 2 3 4 1 1 1 1 1]
 [5 6 7 8 9 1 1 1 1 1]]
[[0 1 2 3 4 1 1 1 1 1]
 [5 6 7 8 9 1 1 1 1 1]]
[[0 1 2 3 4 1 1 1 1 1]
 [5 6 7 8 9 1 1 1 1 1]]


In [43]:
# 10. How to generate custom sequences in numpy without hardcoding?
# Difficulty Level: L2

# Q. Create the following pattern without hardcoding. Use only numpy functions and the below input array a.

# Input:

# a = np.array([1,2,3])
# Desired Output:

# > array([1, 1, 1, 2, 2, 2, 3, 3, 3, 1, 2, 3, 1, 2, 3, 1, 2, 3])
a = np.array([1, 2, 3])
print(a)
print(np.append(arr=np.repeat(a=a, repeats=3), values=[a, a, a]))
print(np.append(arr=np.repeat(a=a, repeats=3), values=np.tile(a, 3)))
print(np.r_[np.repeat(a, 3), np.tile(a, 3)])
print(np.hstack(tup=(np.repeat(a, 3), np.tile(a, 3))))
print(np.concatenate([np.repeat(a, 3), np.tile(a, 3)]))

[1 2 3]
[1 1 1 2 2 2 3 3 3 1 2 3 1 2 3 1 2 3]
[1 1 1 2 2 2 3 3 3 1 2 3 1 2 3 1 2 3]
[1 1 1 2 2 2 3 3 3 1 2 3 1 2 3 1 2 3]
[1 1 1 2 2 2 3 3 3 1 2 3 1 2 3 1 2 3]
[1 1 1 2 2 2 3 3 3 1 2 3 1 2 3 1 2 3]


In [44]:
# 11. How to get the common items between two python numpy arrays?
# Difficulty Level: L2

# Q. Get the common items between a and b

# Input:

# a = np.array([1,2,3,2,3,4,3,4,5,6])
# b = np.array([7,2,10,2,7,4,9,4,9,8])
# Desired Output:

# array([2, 4])

a = np.array([1, 2, 3, 2, 3, 4, 3, 4, 5, 6])
b = np.array([7, 2, 10, 2, 7, 4, 9, 4, 9, 8])
np.intersect1d(a, b)

array([2, 4])

In [45]:
# 12. How to remove from one array those items that exist in another?
# Difficulty Level: L2

# Q. From array a remove all items present in array b

# Input:

# a = np.array([1,2,3,4,5])
# b = np.array([5,6,7,8,9])
# Desired Output:

# array([1,2,3,4])
a = np.array([1, 2, 3, 4, 5])
b = np.array([5, 6, 7, 8, 9])
np.setdiff1d(a, b)

array([1, 2, 3, 4])

In [46]:
# 13. How to get the positions where elements of two arrays match?
# Difficulty Level: L2

# Q. Get the positions where elements of a and b match

# Input:

# a = np.array([1,2,3,2,3,4,3,4,5,6])
# b = np.array([7,2,10,2,7,4,9,4,9,8])
# Desired Output:

# > (array([1, 3, 5, 7]),)
a = np.array([1, 2, 3, 2, 3, 4, 3, 4, 5, 6])
b = np.array([7, 2, 10, 2, 7, 4, 9, 4, 9, 8])
np.where(a == b)

(array([1, 3, 5, 7], dtype=int64),)

##### 14. How to extract all numbers between a given range from a numpy array?
##### Difficulty Level: L2
##### Q. Get all items between 5 and 10 from a.
##### Input:
##### a = np.array([2, 6, 1, 9, 10, 3, 27])
##### Desired Output:
##### (array([6, 9, 10]),)

In [47]:

a = np.array([2, 6, 1, 9, 10, 3, 27])
print(a[np.where(((a >= 5) & (a <= 10)))])
print(a[(a >= 5) & (a <= 10)])
print(a[np.logical_and((a >= 5), (a <= 10))])

[ 6  9 10]
[ 6  9 10]
[ 6  9 10]


##### 15. How to make a python function that handles scalars to work on numpy arrays?
##### Difficulty Level: L2
##### Q. Convert the function maxx that works on two scalars, to work on two arrays.
##### Input:
```
def maxx(x, y):
     """Get the maximum of two items"""
     if x >= y:
         return x
     else:
         return y

maxx(1, 5)
#> 5
```
##### Desired Output:
```
a = np.array([5, 7, 9, 8, 6, 4, 5])
b = np.array([6, 3, 4, 8, 9, 7, 1])
pair_max(a, b)
#> array([ 6.,  7.,  9.,  8.,  9.,  7.,  5.])
```

In [48]:
def maxx(x, y):
    """Get the maximum of two items"""
    if x >= y:
        return x
    else:
        return y


a = np.array([5, 7, 9, 8, 6, 4, 5])
b = np.array([6, 3, 4, 8, 9, 7, 1])
pair_max = np.vectorize(maxx, otypes=[float])
pair_max(a, b)

array([6., 7., 9., 8., 9., 7., 5.])

In [53]:
# 16. How to swap two columns in a 2d numpy array?
# Difficulty Level: L2

# Q. Swap columns 1 and 2 in the array arr.

# arr = np.arange(9).reshape(3,3)
# arr

arr = np.arange(9).reshape(3, 3)
print(arr)
arr[:, [1, 0, 2]]

[[0 1 2]
 [3 4 5]
 [6 7 8]]


array([[1, 0, 2],
       [4, 3, 5],
       [7, 6, 8]])

In [55]:
# 17. How to swap two rows in a 2d numpy array?
# Difficulty Level: L2

# Q. Swap rows 1 and 2 in the array arr:

# arr = np.arange(9).reshape(3,3)
# arr
arr = np.arange(9).reshape(3,3)
print(arr)
arr[[1,0,2],:]

[[0 1 2]
 [3 4 5]
 [6 7 8]]


array([[3, 4, 5],
       [0, 1, 2],
       [6, 7, 8]])