# link - https://www.machinelearningplus.com/python/101-numpy-exercises-python/

In [1]:
# 1. Import numpy as np and see the version
import numpy as np
np.__version__

'1.25.1'

In [2]:
# 2. How to create a 1D array?
# Difficulty Level: L1

# Q. Create a 1D array of numbers from 0 to 9

# Desired output:

# > array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

print(np.array(object=range(0, 10)))
print(np.arange(10))

[0 1 2 3 4 5 6 7 8 9]
[0 1 2 3 4 5 6 7 8 9]


In [3]:
# 3. How to create a boolean array?
# Difficulty Level: L1

# Q. Create a 3×3 numpy array of all True’s

print(np.full(shape=(3, 3), fill_value=True, dtype=bool))
print(np.ones(shape=(3, 3), dtype=bool))

[[ True  True  True]
 [ True  True  True]
 [ True  True  True]]
[[ True  True  True]
 [ True  True  True]
 [ True  True  True]]


In [4]:
# 4. How to extract items that satisfy a given condition from 1D array?
# Difficulty Level: L1

# Q. Extract all odd numbers from arr

# Input:

# arr = np.array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])
# Desired output:

# > array([1, 3, 5, 7, 9])
arr = np.array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])
condition = np.mod(arr, 2) != 0
print(np.extract(condition=condition, arr=arr))

print(arr[arr % 2 == 1])

[1 3 5 7 9]
[1 3 5 7 9]


In [7]:
# 5. How to replace items that satisfy a condition with another value in numpy array?
# Difficulty Level: L1

# Q. Replace all odd numbers in arr with -1

# Input:

# arr = np.array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])
# Desired Output:

# >  array([ 0, -1,  2, -1,  4, -1,  6, -1,  8, -1])
arr = np.array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])
arr[arr % 2 != 0] = -1
arr

array([ 0, -1,  2, -1,  4, -1,  6, -1,  8, -1])

In [12]:
# 6. How to replace items that satisfy a condition without affecting the original array?
# Difficulty Level: L2

# Q. Replace all odd numbers in arr with -1 without changing arr

# Input:

# arr = np.array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])
# Desired Output:
# out
# >  array([ 0, -1,  2, -1,  4, -1,  6, -1,  8, -1])
# arr
# >  array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])
arr = np.array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])
print(np.where(arr % 2 == 1, -1, arr))
print(arr)

[ 0 -1  2 -1  4 -1  6 -1  8 -1]
[0 1 2 3 4 5 6 7 8 9]


In [20]:
# 7. How to reshape an array?
# Difficulty Level: L1

# Q. Convert a 1D array to a 2D array with 2 rows

# Input:

# np.arange(10)

# > array([ 0, 1, 2, 3, 4, 5, 6, 7, 8, 9])
# Desired Output:

# > array([[0, 1, 2, 3, 4],
# >        [5, 6, 7, 8, 9]])
arr = np.arange(10)
print(arr)
print(arr.shape)
print(np.reshape(arr, (2, 5)))
arr2 = np.arange(10)
print(np.reshape(arr2, (2, -1)))

[0 1 2 3 4 5 6 7 8 9]
(10,)
[[0 1 2 3 4]
 [5 6 7 8 9]]
[[0 1 2 3 4]
 [5 6 7 8 9]]
